id: P54C08941
initial_creation_type: input
source_metadata:
  title: Geshe Chekhawa Yeshe Dorje
  language: bo
  description: 'Texts by the famous Kadampa geshe Chekhawa Yeshe Dorje (''chad kha
    ba ye shes rdo rje, 1101–1175):'
  volume:
    d0218895f5d34942b75f66014f340754:
      title: Seven Points of Training the Mind According to the Great Vehicle
      parent: null
created_at: '2022-02-28T23:23:01.282150'
last_modified_at: '2022-02-28T23:23:01.282156'
